Repository Kubanacode/KubanaBook-Front, pull requests merged in 2020-03, with the labels that each got.

#11 Add logout button and modify snackbar position
  src/assets/logout.svg
  src/components/navBar/index.js
  src/components/navBar/navBar.css
  src/components/sackBar/snack.css
  src/pages/feed/index.js
  src/pages/home/index.js
  src/pages/notify/index.js
  src/pages/perfil/index.js
  src/pages/post/index.js
Labels: Hot Fix, New Feature

#12 Create NavBarTop
  package-lock.json
  src/assets/menu.svg
  src/components/navBar/navBar.css
  src/components/navBarTop/index.js
  src/components/navBarTop/navBarTop.css
  src/pages/home/home.css
  src/pages/home/index.js
Labels: New Feature

#13 hotfix
  src/components/navBar/navBar.css
Labels: Hot Fix

#16 Add the navBarTop in all pages and add a new style
  src/components/navBarTop/navBarTop.css
  src/pages/feed/feed.css
  src/pages/feed/index.js
  src/pages/home/home.css
  src/pages/notify/index.js
  src/pages/notify/notify.css
  src/pages/perfil/index.js
  src/pages/perfil/perfil.css
  src/pages/post/index.js
  src/pages/post/post.css
Labels: New Feature, Style

#17 Changes Icons and search color font
  package-lock.json
  src/assets/add.svg
  src/assets/feed.svg
  src/assets/home.svg
  src/assets/logout.svg
  src/assets/menu.svg
  src/assets/notify.svg
  src/assets/perfil.svg
  src/components/navBar/index.js
  src/components/navBar/navBar.css
  src/components/navBarTop/index.js
  src/components/navBarTop/navBarTop.css
  src/pages/home/home.css
  src/pages/home/index.js
Labels: Hot Fix, New Feature

#19 Colocação de tooltips e modificação de profile/notify
  package-lock.json
  src/components/navBar/index.js
  src/pages/profile/index.js
  src/pages/profile/profile.css
  src/routes/router.js
Labels: Hot Fix, New Feature

#20 Create Sign In/Out Pages and add Axios and Redux
  .gitignore
  package.json
  src/App.js
  src/Redux.js
  src/components/navBar/index.js
  src/config/api.js
  src/config/store.js
  src/index.js
  src/pages/profile/index.js
  src/pages/user/signIn.js
  src/pages/user/signOut.js
  src/pages/user/user.css
  src/routes/router.js
  yarn.lock
Labels: Dependence, New Feature

#22 Cr sandbox
  package.json
  src/assets/LogoFB.png
  src/components/navBar/index.js
  src/components/navBarTop/index.js
  src/components/navBarTop/navBarTop.css
  src/components/sackBar/index.js
  src/components/sackBar/snack.css
  src/index.css
  src/pages/feed/feed.css
  src/pages/feed/index.js
  src/pages/home/home.css
  src/pages/home/index.js
  src/pages/notify/index.js
  src/pages/notify/notify.css
  src/pages/post/index.js
  src/pages/post/post.css
  src/pages/profile/index.js
  src/pages/profile/profile.css
  yarn.lock
Labels: Dependence, New Feature, Style, bug
